version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=ap-south-1
      - REPO_NAME=brain-task-app
      - IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:latest
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 850995563020.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $IMAGE_URI .
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $IMAGE_URI
      
artifacts:
  files:
    - k8s/*.yaml
    - buildspec.yml