apiVersion: v1
kind: Service
metadata:
  name: brain-task-service
spec:
  type: LoadBalancer
  selector:
    app: brain-task-app
  ports:
    - protocol: TCP
      port: 3000       # external port
      targetPort: 80   # internal container port
